dist: trusty
language: elixir
elixir: 1.6.5
otp_release: 20.3
addons:
  postgresql: 9.6
env:
  global:
    - MIX_ENV=test
    - HEXPM_PATH=..
    - HEXWEB_PATH=..
  matrix:
    - HEX_VERSION=master
    - HEX_VERSION=v0.17.7
    - HEX_VERSION=v0.16.1
    - HEX_VERSION=v0.15.0
    - HEX_VERSION=v0.14.1
before_script:
  - mix ecto.create
  - git clone https://github.com/hexpm/hex hex -b ${HEX_VERSION} --depth 1
script:
  - mix test --include integration
  - cd hex; mix deps.get && mix test --include integration; cd ..
  - mix run priv/repo/seeds.exs
notifications:
  recipients:
  - eric.meadows.jonsson@gmail.com
  slack:
    secure: D21dsphy22i/G+yujf1V4f2x9pnbmTr2BkZv3nifXggTXY+ObItQ2MM/j9AoObdusbV63eSpvBZTIfX/oe7DQjN8hHBc/aILMZMLq7gKpOCTLtWIVvS9vNkyLa33EWwF/CsMiYQh377vye8a7cvORlkPmf+rNV//E9mbpuIWzBI=
