dist: trusty
language: elixir
elixir: 1.9.0
otp_release: 22.0
addons:
  postgresql: 9.6
env:
  global:
    - MIX_ENV=test
    - HEXPM_PATH=..
    - HEXWEB_PATH=..
  matrix:
    - HEX_VERSION=master
    - HEX_VERSION=v0.19.0
    - HEX_VERSION=v0.18.2
    - HEX_VERSION=v0.17.8
    - HEX_VERSION=v0.16.1
    - HEX_VERSION=v0.15.0
    - HEX_VERSION=v0.14.1
before_script:
  - git clone https://github.com/hexpm/hex hex -b ${HEX_VERSION} --depth 1
script:
  - mix test --include integration
  - sudo cat /var/log/postgresql/postgresql-9.6-main.log
  - mix run priv/repo/seeds.exs
  - cd hex; mix deps.get; cd ..
  - cd hex; mix test --include integration; cd ..
notifications:
  recipients:
  - eric.meadows.jonsson@gmail.com
